name: Hello Selfhosted Runner

on: 
    workflow_dispatch:

jobs:
    say_hello:
#    name: Hello
    runs-on: self-hosted
    steps:
        - name: Checkout
            uses: actions/checkout@v2
            with:
                refs: ${{ github.ref }}
        - name: Hello
            run : bash hello.sh
