name: Hello Selfhosted Runner

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:
    inputs:
      name: 
        description: 'Name'
        required: true
        default: "terada"
        type: string 
    
      major_no:
        description: 'FW Major Number'
        required: true
        default: '3'
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10

env:
  Name: terada
  major_no: '3'
  
jobs:
  say_hello:
    runs-on: self-hosted
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Hello
        run : bash hello.sh
      - name: Echo Dispatch_Name
        run: | 
          echo "Name: $Name"
          echo "Major_no: $Major_no"
          echo $PATH
          pwd
        env:
          Name: ${{ inputs.name }}
          Major_no: ${{ inputs.major_no }}