name: Hello Selfhosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name: 
       description: 'Name'
       required: true

jobs:
  say_hello:
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Hello
      run : bash hello.sh
