name: Hello Selfhosted Runner
on: workflow_dispatch

jobs:
hello:
    name: Hello
    runs-on: self-hosted
    steps:
    - name: Checkout
        uses: actions/checkout@v4
    - name: Hello
        run : bash hello.sh
